version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: comments_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - 127.0.0.1:8000:8000
    command: /start

  pycharm:
    <<: *django
    ports: []
    image: comments_local_pycharm
    command: bash

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: comments_local_postgres
    container_name: comments_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - 127.0.0.1:5433:5432
